name: Lint and test
on:
  push:
    branches-ignore:
      - 'dependabot/**'
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2.3.1
      - name: install-dependencies
        uses: bahmutov/npm-install@v1
      - name: install docs gem
        run: |
          sudo gem install chef-utils -v 16.6.14
          sudo gem install mdl
      - name: eslint
        run: yarn lint
      - name: typecheck
        run: yarn typecheck
      - name: run tests and publish coverage
        uses: paambaati/codeclimate-action@v2.7.5
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
        with:
          coverageCommand: yarn test --coverageDirectory=. --coverage
      - name: lint docs
        run: |
          mdl README.md
          mdl docs/
