name: Lint and test
on:
  push:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2.3.1
      - name: install-dependencies
        uses: bahmutov/npm-install@v1
      - name: install docs gem
        run: |
          gem install chef-utils -v 16.6.14
          gem install mdl
      - name: eslint
        uses: wearerequired/lint-action@v1
        with:
          eslint: true
          eslint_dir: scr
          eslint_extensions: tsx,ts
      - name: typecheck
        run: yarn typecheck
      - name: lint docs
        run: |
          mdl README.md
          mdl docs/
      - name: run tests and publish coverage
        uses: paambaati/codeclimate-action@v2.7.5
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
        with:
          coverageCommand: yarn test --coverageDirectory=. --coverage
