name: Lint and test
on:
  push:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2.3.1
      - name: install-dependencies
        uses: bahmutov/npm-install@v1
      - name: install docs gem
        run: |
          gem install chef-utils -v 16.6.14 --install-dir /usr/local/bin/ruby/gems
          gem install mdl --install-dir /usr/local/bin/ruby/gems
      - name: eslint
        run: yarn lint
      - name: typecheck
        run: yarn typecheck
      - name: run tests and publish coverage
        uses: paambaati/codeclimate-action@v2.7.5
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
        with:
          coverageCommand: yarn test --coverageDirectory=. --coverage
      - name: lint docs
        run: |
          ls -a /usr/local/bin/ruby/gems/bin
          PATH=/usr/local/bin/ruby/gems/bin:$PATH mdl README.md
          PATH=/usr/local/bin/ruby/gems/bin:$PATH mdl docs/
